const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const file=path.resolve(root,'.'+(rel==='/'?'/index.html':rel));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,d)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.json':'application/json'})[path.extname(file)]||'application/octet-stream');res.end(d);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1280,height:850},serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;});await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'load'});
 const report=await page.evaluate(async()=>{
  const checks=[],check=(n,v)=>{if(!v)throw Error(n);checks.push(n);};options.sfx=0;options.bgm=0;
  function fresh(id){meta=defaultMeta();meta.charLevel=5;meta.gold=10000;meta.soul=1000;const j=ADVANCED_JOBS.find(j=>j.id===id);meta.appearance=j.base;chooseAdvancement(id);startRun();spawnTimer=999;state.nextWaveAt=999;player.invuln=999;enemies=[];}
  function enemy(d=100){const e=spawnNormalEnemy('goblin',{x:player.x+d,y:player.y});e.hp=e.maxHp=100000;e.speed=0;return e;}
  for(const j of ADVANCED_JOBS){fresh(j.id);const image=advImage(j.id);await image.decode();const icon=new Image();icon.src=j.iconImg;await icon.decode();check(j.id+' art loaded',image.naturalWidth===2172&&icon.naturalWidth>0);check(j.id+' kit',player.adv.id===j.id&&player.skills.Q.name===j.q&&player.skills.E.name===j.e);enemy();performBasicAttack();check(j.id+' basic attacks',enemies[0].hp<enemies[0].maxHp||projectiles.length>0);useSkill('Q');check(j.id+' Q cooldown',player.skills.Q.cd>0);for(let n=0;n<60;n++){updateAdvancements(1/60);updateTimedAttacks(1/60);}if(j.id==='berserker')player.hp=player.maxHp*.25;useSkill('E');if(j.random){check(j.id+' rolling cooldown frozen',player.skills.E.cd===0);updateAdvancements(1.2);check(j.id+' held 10 sec',player.skills.E.roulette.phase==='held'&&player.skills.E.roulette.time===10);useSkill('E');}check(j.id+' E cooldown',player.skills.E.cd>0);for(let n=0;n<240;n++)updateAdvancements(1/60);render();updateHud();check(j.id+' finite state',Number.isFinite(player.hp)&&Number.isFinite(player.x));}
  fresh('warlock');enemy();useSkill('E');useSkill('E');check('repeated press while rolling ignored',player.skills.E.roulette.phase==='rolling');updateAdvancements(1.2);const result=JSON.stringify(player.skills.E.roulette.result);updateAdvancements(9);check('held choice stable for nine seconds',player.skills.E.cd===0&&JSON.stringify(player.skills.E.roulette.result)===result&&player.skills.E.roulette.time===1);
  const remain=player.skills.E.roulette.time;state.mode='paused';update(2);check('pause freezes hold',player.skills.E.roulette.time===remain);state.mode='playing';updateAdvancements(1.01);check('expired choice discarded, cooldown starts',player.skills.E.roulette.phase==='ready'&&player.skills.E.cd===30&&player.adv.fx.length===0);useSkill('E');check('cooldown blocks reroll',player.skills.E.roulette.phase==='ready');
  fresh('magician');enemy();useSkill('E');updateAdvancements(1.2);updateAdvancements(2);useSkill('E');check('held confirm consumes exactly once',player.skills.E.roulette.result===null&&player.skills.E.cd>28);const count=player.adv.fx.length;useSkill('E');check('double confirm blocked',player.adv.fx.length===count);
  for(const id of ['demon','curse','revive','ace']){fresh('warlock');const e=enemy();executeRouletteResult(id==='ace'?{id,name:'ace',refund:.03}:WARLOCK_RESULTS.find(r=>r.id===id));for(let i=0;i<60;i++)updateAdvancements(1/60);if(id==='revive'){e.hp=1;killEnemy(e);player.hp=player.maxHp*.5;player.x=e.x;const hp=player.hp;updateAdvancements(.1);check('revive death field heals',player.hp>hp);}else check(id+' damages',e.hp<e.maxHp);}
  fresh('magician');executeRouletteResult({id:'ace',name:'ace',refund:.03});player.skills.E.cd=30;player.skills.E.roulette={phase:'held',time:10,result:{id:'ace',name:'ace',refund:.03}};player.skills.E.cd=0;useSkill('E');check('ace cooldown refund',Math.abs(player.skills.E.cd-29.1)<.001);
  for(const j of ADVANCED_JOBS.filter(j=>!j.random)){fresh('magician');enemy();executeRouletteResult({id:'joker',name:'joker',borrowed:j.id});for(let i=0;i<60;i++)updateAdvancements(1/60);performBasicAttack();check('joker '+j.id,player.adv.fx.length>0||player.adv.allies.length>0||player.adv.blood>0||player.adv.holy>0||player.adv.frenzy>0||enemies[0].hp<enemies[0].maxHp);}
  fresh('magician');const random=Math.random;const draws=[.9,3.1/11,.9];Math.random=()=>draws.shift()??.5;const nested=rollAdvResult('magician');Math.random=random;check('joker can copy resolved warlock result',nested.borrowed==='warlock'&&nested.nestedResult.id==='revive');executeRouletteResult(nested);check('copied warlock result executes without another roulette',player.adv.revive===20&&player.skills.E.roulette.phase==='ready');
  fresh('berserker');useSkill('E');check('berserker health gate no wasted cooldown',player.skills.E.cd===0);player.hp=player.maxHp*.25;useSkill('E');check('berserker shield and attack speed',player.shield>0&&advancementAttackSpeed()===.5);updateAdvancements(8.01);check('berserker buff expires',advancementAttackSpeed()===0);
  fresh('commander');const foe=enemy(240);useSkill('E');for(let i=0;i<360;i++)updateAdvancements(1/60);check('knights independently approach and hit',foe.hp<foe.maxHp&&player.adv.allies.length===3);updateAdvancements(13);check('knights expire',!player.adv.allies.length);
  fresh('honggildong');enemy();useSkill('E');performBasicAttack();check('two attack echo clones',player.adv.fx.filter(f=>f.kind==='echo').length===2);updateAdvancements(5.1);check('clones expire',player.adv.clones===0);
  fresh('paladin');const close=enemy(30);player.hp=player.maxHp*.5;useSkill('E');updateAdvancements(.1);check('paladin blocks normal enemies',dist(player.x,player.y,close.x,close.y)>=145);const hp=player.hp;updateAdvancements(3);check('paladin release heals',player.hp>hp);
  fresh('madmonk');const boss=enemy();boss.isBoss=true;for(let i=0;i<50;i++){dealDamageToEnemy(boss,1,false);updateAdvancements(.51);}check('madmonk builds on boss hits and caps',player.adv.rage===20);updateAdvancements(6.1);check('madmonk rage expires',player.adv.rage===0);
  fresh('dragon');const gold=meta.gold,soul=meta.soul;chooseAdvancement('dragon');check('owned switch free',meta.gold===gold&&meta.soul===soul);check('cross base rejected',!chooseAdvancement('warlock'));const saved=normalizeMeta(JSON.parse(JSON.stringify(meta)));check('selection survives save normalization',saved.advancements.selected.warrior==='dragon');check('invalid advancement rejected',!normalizeMeta({advancements:{owned:['evil'],selected:{mage:'evil'}}}).advancements.owned.length);
  const stored=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('quota');};const prior=JSON.stringify(meta.advancements);const money=meta.gold;check('failed save rolls back purchase',!chooseAdvancement('berserker')&&meta.gold===money&&JSON.stringify(meta.advancements)===prior);Storage.prototype.setItem=stored;saveMeta();
  fresh('warlock');useSkill('E');updateAdvancements(1.2);const hold=player.skills.E.roulette.time;player.dying=true;update(.1);check('death stops hold',player.skills.E.roulette.time===hold);startRun();check('new run clears roulette',player.skills.E.roulette.phase==='ready');
  showScreen('lobby');renderLobbyAll();openJobModal();check('three branch cards',document.querySelectorAll('.adv-card').length===3);return checks;
 });
 fs.mkdirSync(path.join(root,'test-results'),{recursive:true});await page.screenshot({path:path.join(root,'test-results/advancements-desktop.png'),animations:'disabled'});
 await page.setViewportSize({width:390,height:844});await page.locator('#job-modal .modal-inner').evaluate(e=>{e.scrollTop=0;});await page.screenshot({path:path.join(root,'test-results/advancements-mobile.png'),animations:'disabled'});assert(await page.locator('#job-card-row').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert(await page.locator('#job-modal .modal-inner').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&e.scrollHeight>e.clientHeight;}));
 await page.evaluate(()=>{jobModal.classList.add('hidden');startRun();useSkill('E');updateAdvancements(1.2);state.camera.x=player.x-canvas.width/2;state.camera.y=player.y-canvas.height/2;render();updateHud();});
 await page.screenshot({path:path.join(root,'test-results/roulette-mobile.png'),animations:'disabled'});assert(await page.locator('#roulette-hud').isVisible());
 await page.locator('#hotbar [data-slot="E"]').click();assert(await page.evaluate(()=>player.skills.E.cd>0&&player.skills.E.roulette.phase==='ready'));
 await page.evaluate(()=>{player.skills.E.cd=0;});await page.keyboard.press('e');assert(await page.evaluate(()=>player.skills.E.roulette.phase==='rolling'));
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'test-results/advancement-checks.json'),JSON.stringify({passed:report.length+5,checks:report,pageErrors:errors},null,2));console.log(JSON.stringify({passed:report.length+5,pageErrors:errors}));
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
